### ISSUE TITLE
Include a specification for a "cose profile" used by Epoch Bells

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats/draft-birkholz-rats-epoch-marker#12]
Maybe already aligned with the upcoming COSE profile -00?

**Comment by thomas-fossati** [comment]
see https://datatracker.ietf.org/doc/draft-fossati-cose-profiles/

**Comment by thomas-fossati** [comment]
as agreed, use the URL form for now (pointing to the draft name)

**Comment by henkbirkholz** [comment]
using draft name as profile uri for now

**Comment by henkbirkholz** [comment]
ha, jinx... +1

**Comment by henkbirkholz** [comment]
coming back to this as a WG item
