### ISSUE TITLE
complete CBOR replacement for RFC3161?

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats/draft-birkholz-rats-epoch-marker#18]
[...]

There's a bigger question though: is this CBOR tst-info something that we can define in isolation?  Or should it be more proper to do a full COSE translation of RFC3161?

_Originally posted by @thomas-fossati in https://github.com/ietf-rats/draft-birkholz-rats-epoch-marker/pull/16#discussion_r1133686965_

**Comment by cabo** [comment]
I think we should do all of 3161, possibly in a separate document (or for convenience, here).
The sign request looks similar enough to the signed timestamp that this is little additional material.

**Comment by thomas-fossati** [comment]
Since I am going to be a Helvetian in just a few months, I decide to declare neutrality :-)

**Comment by thomas-fossati** [comment]
Since I am going to be a Helvetian in just a few months, I decide to declare neutrality :-)

**Comment by henkbirkholz** [comment]
please materialize in #16, according to https://github.com/ietf-rats/draft-birkholz-rats-epoch-marker/pull/16#pullrequestreview-1337599629

**Comment by henkbirkholz** [comment]
most of it is done in #16 
Open action items are currently inline notes in the I-D. Those can become working group items later.
