### ISSUE TITLE
Random Generator EPOCH

### ISSUE THREAD

**Issue by yogeshbdeshpande** [ietf-rats/draft-birkholz-rats-epoch-marker#2]
EPOCH data model should have a mechanism to exchange a Random Number based on
an agreed protocol between the Sender and the Receiver.

**Comment by henkbirkholz** [comment]
Like a symmetric private key that is known only by the Epoch Bell and a requster, established out-of-band, and functioning like... "extradata" when processing the nonce from a challenge-response quested by the Epoch Bell? We might need a tad bit more detail on the usage scenario.

**Comment by yogeshbdeshpande** [comment]
Correct. I will try to draw a scenario and we can discuss further!

**Comment by henkbirkholz** [comment]
This is still open, right? We'll submit without for now.

**Comment by henkbirkholz** [comment]
Abandoning this issue. Can be reissued as a working group item.
