### ISSUE TITLE
tdate as epoch

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats/draft-birkholz-rats-epoch-marker#21]
tdate is a reasonable `tagged-epoch-id` given Evidence contains a timestamp in `tdate` format and a reference value is expressed in terms of a grace period within which the timestamp falls, relative to the epoch id.

**Comment by henkbirkholz** [comment]
why #6.0 and not #6.1? We are using CBOR.

**Comment by nedmsmith** [comment]
#6.0 implies a translation to #6.1 before any math can be applied. #6.1 and #6.1001 implies a translation to #6.0 if human readable representation is needed.
