### ISSUE TITLE
Carl's early review

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats/draft-birkholz-rats-epoch-marker#23]
I realize it may be a bit early to review the draft, but I gave it a read and had some comments and questions. 

- How/where is this intended to be used? Some elements seem useful to conveying a (pool of) nonces that would be used in a claim like eat_nonce, others seem like they would serve as a new claim type (i.e., the 3161-focused options).
- What is Concise Evidence? It is listed as alternative to EAT in section 4.
- The draft is currently a description of a format. It might benefit from sections describing creation and verification (or at least some considerations for each). 
- Is the epoch-marker structure intended to be authenticated? Some of the options can be authenticated already, i.e., 4.1.2 and 4.1.7. It's not clear what the plan is for the top level (or if encryption is required).
- It's not clear to me what the “never-repeating byte string” phrase in sections 4.1.4 and 4.1.5 means? Is this phrase intended to avoid confusion because the nonces may be used one time by multiple parties? As written, it could be read as referring to the contents of the value.
- Are each of the possible types applicable to each model? 
- For the RFC3161-based types, what does the message imprint in response cover, i.e., what data was hashed? This seems likely to vary with the model.
- In section 4.1.2, it's probably worth explicitly excluding failed RFC3161 responses or maybe just conveying the timeStampToken field instead of the response.
- Section 4.1.7 describes a "stateless nonce" but there is state, i.e., the symmetric key and synchronized clocks. To assure one time use, there would also need to be state up until some window size elapses. This feels a bit like TOTP (RFC6238), in which case, why is the time field needed at all? If you want to use a key and a time value, just use one of the timestamp token options.
- It'd be helpful to include words on nonce handling for unsolicited and subscription models and how this varies for each role (since storage burden will vary for attester and verifier, for example). 
- Section 7.3 of draft-ietf-rats-reference-interaction-models-07 states "While a Handle Distributor is not required in this model, it is also limited to bi-lateral subscription relationships in which each Verifier has to create and provide its individual Handle." This suggests reuse is possible.
- Given the ordering requirements on multi-nonce, this feels less like a nonce and more like a one-time pad. Some words on what happens if a message gets lost would be helpful. Ought this type require the verifier to be able to distinguish between attesters (in order to maintain state)? Given the ordering requirement, probably worth noting storage burden is diminished for the verifier.

**Comment by henkbirkholz** [comment]
> What is Concise Evidence? It is listed as alternative to EAT in section 4.

I'll take this one. It should be a matter of days for the reference to be public for informative reference.

**Comment by henkbirkholz** [comment]
> Is the epoch-marker structure intended to be authenticated? Some of the options can be authenticated already, i.e., 4.1.2 and 4.1.7. It's not clear what the plan is for the top level (or if encryption is required).

Only Stateless Nonce is symmetrically signed (like a cookie with a proof of origin attached to it - am minimal pop). but not 4.1.2 (RFC3161 TST_Info) that is coming without the CMS frosting. Maybe Stateless Nonce should be outsourced into a separate I-D? To keep this one requiring COSE envelopes for every payload?

**Comment by henkbirkholz** [comment]
> It's not clear to me what the “never-repeating byte string” phrase in sections 4.1.4 and 4.1.5 means? Is this phrase intended to avoid confusion because the nonces may be used one time by multiple parties? As written, it could be read as referring to the contents of the value.

Okay... let's say "never-repeating" was a placeholder for n-bits entropy requirements... will fix.

**Comment by henkbirkholz** [comment]
> Are each of the possible types applicable to each model?

Yes. That's the point. But we can spell that out more explicitly.

**Comment by henkbirkholz** [comment]
> In section 4.1.2, it's probably worth explicitly excluding failed RFC3161 responses or maybe just conveying the timeStampToken field instead of the response.

Oh, we are inconsistent in our wording here! We meant to TSTInfo in the description of the field. Will fix.

**Comment by henkbirkholz** [comment]
> Section 4.1.7 describes a "stateless nonce" but there is state, i.e., the symmetric key and synchronized clocks. To assure one time use, there would also need to be state up until some window size elapses. This feels a bit like TOTP (RFC6238), in which case, why is the time field needed at all? If you want to use a key and a time value, just use one of the timestamp token options.

@thomas-fossati will comment more on this later.

**Comment by henkbirkholz** [comment]
> It'd be helpful to include words on nonce handling for unsolicited and subscription models and how this varies for each role (since storage burden will vary for attester and verifier, for example).

Maybe we need to include "nonce handling considerations" not here in epoch markers, but in Section [Uni-Directional Remote Attestation](https://www.ietf.org/archive/id/draft-ietf-rats-reference-interaction-models-07.html#name-uni-directional-remote-atte) (unsolicited) and Section [Streaming Remote Attestation](https://www.ietf.org/archive/id/draft-ietf-rats-reference-interaction-models-07.html#name-streaming-remote-attestatio) (solicited) in I-D.ietf-rats-reference-interaction-models? And then reference those here?

@carl-wallace, what do you think?

**Comment by henkbirkholz** [comment]
> Section 7.3 of draft-ietf-rats-reference-interaction-models-07 states "While a Handle Distributor is not required in this model, it is also limited to bi-lateral subscription relationships in which each Verifier has to create and provide its individual Handle." This suggests reuse is possible.

Reusing the term nonce here, although it is obviously defined as being re-usable in a given scope of subscribers and in the scope of an epoch, it nevertheless felt prudent to us to create that mental association. If that association with nonce and "epoch extra-data that spawn from a huge amount of entropy" is more confusing than helping, should we rephrase the whole use pf multi-nonce-(lists)?

**Comment by thomas-fossati** [comment]
> should we rephrase the whole use pf multi-nonce-(lists)?

yes, please :-)

**Comment by thomas-fossati** [comment]
> Given the ordering requirements on multi-nonce, this feels less like a nonce and more like a one-time pad

I guess you mean "one-time password" here?

> Some words on what happens if a message gets lost would be helpful.

excellent point.

> Ought this type require the verifier to be able to distinguish between attesters (in order to maintain state)? 

This is not needed since attesters are distinguished based on their cryptographic identity (which is used to sign the specific "multi-nonce").

> Given the ordering requirement, probably worth noting storage burden is diminished for the verifier.

For each epoch, the verifier needs to keep the whole list in memory, as well as per-attester consumption state.  So, the storage requirements are actually increased compared to the simple "multi-nonce" case.

**Comment by carl-wallace** [comment]
> > For the RFC3161-based types, what does the message imprint in response cover, i.e., what data was hashed? This seems likely to vary with the model.
> 
> Good catch. The vital part here is the timestamp and the signature and not the input to message imprint. Hence, the bell can send whatever it wants to a trusted TSA. Do we want to provide recommendations here what you send? It could bea fixed byte array, like a magic number. Whould that be addressing this comment?



> > It'd be helpful to include words on nonce handling for unsolicited and subscription models and how this varies for each role (since storage burden will vary for attester and verifier, for example).
> 
> Maybe we need to include "nonce handling considerations" not here in epoch markers, but in Section [Uni-Directional Remote Attestation](https://www.ietf.org/archive/id/draft-ietf-rats-reference-interaction-models-07.html#name-uni-directional-remote-atte) (unsolicited) and Section [Streaming Remote Attestation](https://www.ietf.org/archive/id/draft-ietf-rats-reference-interaction-models-07.html#name-streaming-remote-attestatio) (solicited) in I-D.ietf-rats-reference-interaction-models? And then reference those here?
> 
> @carl-wallace, what do you think?

Writing there and referencing here seems fine.

**Comment by carl-wallace** [comment]
> > Given the ordering requirements on multi-nonce, this feels less like a nonce and more like a one-time pad
> 
> I guess you mean "one-time password" here?

One-time password works. I meant this is more like a list of values that you scratch off after use than a traditional nonce. It's already not a traditional nonce given the reuse by different parties and the ordering requirement is another step away from "nonce." Re-reading it now, I don't think it is unclear what the goal is so it's probably fine.

**Comment by thomas-fossati** [comment]
> > Section 4.1.7 describes a "stateless nonce" but there is state, i.e., the symmetric key and synchronized clocks. To assure one time use, there would also need to be state up until some window size elapses. This feels a bit like TOTP (RFC6238), in which case, why is the time field needed at all? If you want to use a key and a time value, just use one of the timestamp token options.
> 
> @thomas-fossati will comment more on this later.

I have removed the stateless nonce from the draft.  It is a useful construct but I'm more and more convinced it's not a good fit with the overall epoch markers design.

**Comment by henkbirkholz** [comment]
> > The draft is currently a description of a format. It might benefit from sections describing creation and verification (or at least some considerations for each).
> 
> If subsections "Creation Procedure" & "Verification Procedure" for Epoch Marker Payload is implied here, that's an excellent idea. Each subsection of . [Epoch Marker Payloads](https://ietf-rats.github.io/draft-birkholz-rats-epoch-marker/draft-birkholz-rats-epoch-markers.html#name-epoch-marker-payloads) should then follow that structure.

addressed in #24

**Comment by henkbirkholz** [comment]
> > Is the epoch-marker structure intended to be authenticated? Some of the options can be authenticated already, i.e., 4.1.2 and 4.1.7. It's not clear what the plan is for the top level (or if encryption is required).
> 
> Only Stateless Nonce is symmetrically signed (like a cookie with a proof of origin attached to it - am minimal pop). but not 4.1.2 (RFC3161 TST_Info) that is coming without the CMS frosting. Maybe Stateless Nonce should be outsourced into a separate I-D? To keep this one requiring COSE envelopes for every payload?

addressed in https://github.com/ietf-rats/draft-birkholz-rats-epoch-marker/pull/24

**Comment by henkbirkholz** [comment]
> > It's not clear to me what the “never-repeating byte string” phrase in sections 4.1.4 and 4.1.5 means? Is this phrase intended to avoid confusion because the nonces may be used one time by multiple parties? As written, it could be read as referring to the contents of the value.
> 
> Okay... let's say "never-repeating" was a placeholder for n-bits entropy requirements... will fix.

addressed in https://github.com/ietf-rats/draft-birkholz-rats-epoch-marker/pull/24

**Comment by henkbirkholz** [comment]
> > Section 7.3 of draft-ietf-rats-reference-interaction-models-07 states "While a Handle Distributor is not required in this model, it is also limited to bi-lateral subscription relationships in which each Verifier has to create and provide its individual Handle." This suggests reuse is possible.
> 
> Reusing the term nonce here, although it is obviously defined as being re-usable in a given scope of subscribers and in the scope of an epoch, it nevertheless felt prudent to us to create that mental association. If that association with nonce and "epoch extra-data that spawns from a huge amount of entropy" is more confusing than helping, should we rephrase the whole use of multi-nonce-(lists)?

will be a topic at IETF 117

**Comment by henkbirkholz** [comment]
> > It'd be helpful to include words on nonce handling for unsolicited and subscription models and how this varies for each role (since storage burden will vary for attester and verifier, for example).
> 
> Maybe we need to include "nonce handling considerations" not here in epoch markers, but in Section [Uni-Directional Remote Attestation](https://www.ietf.org/archive/id/draft-ietf-rats-reference-interaction-models-07.html#name-uni-directional-remote-atte) (unsolicited) and Section [Streaming Remote Attestation](https://www.ietf.org/archive/id/draft-ietf-rats-reference-interaction-models-07.html#name-streaming-remote-attestatio) (solicited) in I-D.ietf-rats-reference-interaction-models? And then reference those here?
> 
> @carl-wallace, what do you think?

will be a topic at IETF 117

**Comment by henkbirkholz** [comment]
> > What is Concise Evidence? It is listed as alternative to EAT in section 4.
> 
> I'll take this one. It should be a matter of days for the reference to be public for informative reference.

with a little bit of luck, the public reference will be available before the submission cut-off

**Comment by henkbirkholz** [comment]
> > The draft is currently a description of a format. It might benefit from sections describing creation and verification (or at least some considerations for each).
> 
> If subsections "Creation Procedure" & "Verification Procedure" for Epoch Marker Payload is implied here, that's an excellent idea. Each subsection of . [Epoch Marker Payloads](https://ietf-rats.github.io/draft-birkholz-rats-epoch-marker/draft-birkholz-rats-epoch-markers.html#name-epoch-marker-payloads) should then follow that structure.

Moving to after CfA

**Comment by henkbirkholz** [comment]
> > Section 7.3 of draft-ietf-rats-reference-interaction-models-07 states "While a Handle Distributor is not required in this model, it is also limited to bi-lateral subscription relationships in which each Verifier has to create and provide its individual Handle." This suggests reuse is possible.

> Reusing the term nonce here, although it is obviously defined as being re-usable in a given scope of subscribers and in the scope of an epoch, it nevertheless felt prudent to us to create that mental association. If that association with nonce and "epoch extra-data that spawns from a huge amount of entropy" is more confusing than helping, should we rephrase the whole use of multi-nonce-(lists)?

Finally, we made a decision on how to substitute multi-nonce: the proposed name is now Epoch Tick.

**Comment by henkbirkholz** [comment]
Resolved in #24, #25, #27, #28.

Thanks @carl-wallace!
